# Generated by Django 5.1.2 on 2024-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='duration_type',
            field=models.CharField(choices=[('fixed', 'Fixed Number of Days'), ('interval', 'Interval Duration')], default='fixed', max_length=10),
        ),
    ]
