# Generated by Django 5.1.2 on 2024-10-28 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0002_tariff_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in Days'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Fixed Number of Days'), ('period', 'Period Duration')], default='days', max_length=10, verbose_name='Duration Type'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max_visits',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Visits'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tariff Name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
