# Generated by Django 5.1.2 on 2024-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0003_alter_tariff_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='tariff',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
