# Generated by Django 5.1.2 on 2024-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0005_tariff_is_evening_tariff_is_morning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='is_evening',
            field=models.BooleanField(default=False, verbose_name='16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_morning',
            field=models.BooleanField(default=False, verbose_name='08:00-16:00'),
        ),
    ]
