# Generated by Django 5.1.2 on 2024-11-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qra', '0006_alter_tariff_is_evening_alter_tariff_is_morning'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAbonement',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qra.tariff')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qra.userprofile')),
            ],
        ),
    ]
